version: '3.8'

services:
  noctispro:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    command: ["/bin/bash", "-c", "cd /workspace && ./container_start.sh"]
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/workspace
    ports:
      - "80:80"
      - "4040:4040"  # ngrok web interface
