# Generated by Django 5.2.5 on 2025-09-01 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicom_file', models.FileField(upload_to='dicom/')),
                ('instance_number', models.IntegerField(default=1)),
                ('slice_location', models.FloatField(blank=True, null=True)),
                ('rows', models.IntegerField(default=512)),
                ('columns', models.IntegerField(default=512)),
                ('pixel_spacing', models.CharField(blank=True, max_length=50)),
                ('slice_thickness', models.FloatField(blank=True, null=True)),
                ('window_width', models.IntegerField(default=400)),
                ('window_center', models.IntegerField(default=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_images', to='worklist.study')),
            ],
            options={
                'ordering': ['instance_number'],
            },
        ),
    ]
