# Generated by Django 4.2.7 on 2025-08-09 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyattachment',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AddField(
            model_name='studyattachment',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyattachment',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studyattachment',
            name='attached_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by_attachments', to='worklist.study'),
        ),
        migrations.AddField(
            model_name='studyattachment',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studyattachment',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyattachment',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyattachment',
            name='is_current_version',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studyattachment',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studyattachment',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyattachment',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studyattachment',
            name='modality',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studyattachment',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyattachment',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worklist.studyattachment'),
        ),
        migrations.AddField(
            model_name='studyattachment',
            name='study_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='attachment_thumbnails/'),
        ),
        migrations.AddField(
            model_name='studyattachment',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='studyattachment',
            name='file_type',
            field=models.CharField(choices=[('report', 'Report'), ('previous_study', 'Previous Study'), ('dicom_study', 'DICOM Study'), ('word_document', 'Word Document'), ('pdf_document', 'PDF Document'), ('image', 'Image'), ('document', 'Document'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='AttachmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='worklist.studyattachment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttachmentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='attachment_versions/')),
                ('change_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='worklist.studyattachment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('attachment', 'version_number')},
            },
        ),
    ]
