# Generated by Django 4.2.7 on 2025-08-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='ae_title',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
