apiVersion: v1
kind: ConfigMap
metadata:
  name: noctispro-config
  namespace: noctispro
data:
  DJANGO_SETTINGS_MODULE: "noctis_pro.settings"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DICOM_PORT: "11112"
  DICOM_AET: "NOCTIS_SCP"
  WEB_PORT: "8000"
  STATIC_URL: "/static/"
  MEDIA_URL: "/media/"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: noctispro
data:
  nginx.conf: |
    upstream django {
        server noctispro-web:8000;
    }
    
    server {
        listen 80;
        server_name _;
        client_max_body_size 100M;
        
        location /static/ {
            alias /app/staticfiles/;
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
        
        location /media/ {
            alias /app/media/;
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
        
        location / {
            proxy_pass http://django;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }
        
        # Health check endpoint
        location /health {
            access_log off;
            return 200 "healthy\n";
        }
    }