# Generated by Django 4.2.23 on 2025-09-01 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Modalities',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_instance_uid', models.CharField(max_length=255, unique=True)),
                ('study_date', models.DateField()),
                ('study_time', models.TimeField(blank=True, null=True)),
                ('study_description', models.CharField(blank=True, max_length=500)),
                ('accession_number', models.CharField(blank=True, max_length=100)),
                ('referring_physician', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('urgent', 'Urgent')], default='scheduled', max_length=20)),
                ('priority', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worklist.modality')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='worklist.patient')),
            ],
            options={
                'ordering': ['-study_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(max_length=255, unique=True)),
                ('series_number', models.IntegerField()),
                ('series_description', models.CharField(blank=True, max_length=500)),
                ('modality', models.CharField(blank=True, max_length=10)),
                ('body_part_examined', models.CharField(blank=True, max_length=100)),
                ('image_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='worklist.study')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['series_number'],
            },
        ),
        migrations.CreateModel(
            name='DicomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_instance_uid', models.CharField(max_length=255, unique=True)),
                ('instance_number', models.IntegerField()),
                ('file_path', models.FileField(blank=True, null=True, upload_to='dicom/')),
                ('file_size', models.BigIntegerField(default=0)),
                ('image_position', models.CharField(blank=True, max_length=100)),
                ('image_orientation', models.CharField(blank=True, max_length=100)),
                ('pixel_spacing', models.CharField(blank=True, max_length=50)),
                ('slice_thickness', models.FloatField(blank=True, null=True)),
                ('window_center', models.IntegerField(blank=True, null=True)),
                ('window_width', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='worklist.series')),
            ],
            options={
                'ordering': ['instance_number'],
            },
        ),
    ]
