#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   sudo bash ops/install_services.sh
# Behavior:
#   - Automatically detects a usable domain name:
#       1) Host FQDN if it resolves to this server's public IP
#       2) PTR (reverse DNS) name if it resolves back to this server
#       3) Fallback: noctis-<machineid>.<public-ip>.sslip.io
#   - Sets up Nginx, Certbot (non-interactive), Redis, Python venv, systemd units
#   - Prints the final URL to access at the end
# Optional environment variables (no prompts):
#   DUCKDNS_SUBDOMAIN, DUCKDNS_TOKEN  # to also configure a constant DuckDNS name

# Resolve app directory from this script's location
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
VENV_DIR="$APP_DIR/venv"

# Desired bind for ASGI behind nginx
HOST="127.0.0.1"
PORT="8000"

if [ "${EUID:-$(id -u)}" -ne 0 ]; then
	echo "This script must be run with sudo or as root."
	exit 1
fi

# Optional DuckDNS from environment (no interactive args)
DUCKDNS_SUBDOMAIN="${DUCKDNS_SUBDOMAIN:-}"
DUCKDNS_TOKEN="${DUCKDNS_TOKEN:-}"

# Detect public IPv4
IP_ADDR="$(curl -fsS4 ifconfig.me || true)"
if [ -z "$IP_ADDR" ]; then
	IP_ADDR="$(hostname -I 2>/dev/null | awk '{print $1}')"
fi
IP_ADDR=${IP_ADDR:-"127.0.0.1"}

# Try FQDN first if it resolves to this public IP
AUTO_DOMAIN=""
HOST_FQDN="$(hostname -f 2>/dev/null || true)"
if echo "$HOST_FQDN" | grep -q '\.'; then
	if getent ahostsv4 "$HOST_FQDN" | awk '{print $1}' | grep -Fxq "$IP_ADDR"; then
		AUTO_DOMAIN="$HOST_FQDN"
	fi
fi

# Otherwise try PTR (reverse DNS) if it maps back to us
if [ -z "$AUTO_DOMAIN" ]; then
	PTR_DOMAIN="$(getent hosts "$IP_ADDR" | awk 'NR==1{print $2}')"
	if [ -n "$PTR_DOMAIN" ]; then
		if getent ahostsv4 "$PTR_DOMAIN" | awk '{print $1}' | grep -Fxq "$IP_ADDR"; then
			AUTO_DOMAIN="$PTR_DOMAIN"
		fi
	fi
fi

# Fallback to sslip.io-based stable hostname
FALLBACK_DOMAIN=""
if [ -z "$AUTO_DOMAIN" ]; then
	MACHINE_ID="$( (cat /etc/machine-id 2>/dev/null || uuidgen) | tr -d '-' | cut -c1-8 )"
	AUTO_DOMAIN="noctis-$MACHINE_ID.$IP_ADDR.sslip.io"
else
	# Even when we have a real domain, keep a fallback reachable name
	MACHINE_ID="$( (cat /etc/machine-id 2>/dev/null || uuidgen) | tr -d '-' | cut -c1-8 )"
	FALLBACK_DOMAIN="noctis-$MACHINE_ID.$IP_ADDR.sslip.io"
fi

# Optional constant URL via DuckDNS
DUCK_DOMAIN=""
if [ -n "$DUCKDNS_SUBDOMAIN" ] && [ -n "$DUCKDNS_TOKEN" ]; then
	DUCK_DOMAIN="$DUCKDNS_SUBDOMAIN.duckdns.org"
fi

apt-get update -y
apt-get install -y \
	python3 python3-venv python3-dev build-essential \
	libpq-dev libjpeg-dev zlib1g-dev libopenjp2-7 libssl-dev libffi-dev \
	git redis-server nginx certbot python3-certbot-nginx curl

systemctl enable --now redis-server || true

if [ ! -d "$VENV_DIR" ]; then
	python3 -m venv "$VENV_DIR"
fi
# shellcheck disable=SC1090
source "$VENV_DIR/bin/activate"

pip install --upgrade pip wheel setuptools
pip install -r "$APP_DIR/requirements.txt"

"$VENV_DIR/bin/python" "$APP_DIR/manage.py" migrate --noinput
"$VENV_DIR/bin/python" "$APP_DIR/manage.py" collectstatic --noinput

# Write environment file consumed by systemd units
install -d -m 0755 /etc/noctis
# Prefer the auto domain; if DuckDNS provided, use that as the public URL
PUBLIC_HOST="$AUTO_DOMAIN"
if [ -n "$DUCK_DOMAIN" ]; then
	PUBLIC_HOST="$DUCK_DOMAIN"
fi
PUBLIC_URL="http://$PUBLIC_HOST/"
cat > /etc/noctis/noctis.env <<EOF
# Generated by ops/install_services.sh
APP_DIR=$APP_DIR
VENV_DIR=$VENV_DIR

DJANGO_SETTINGS_MODULE=noctis_pro.settings
ASGI_APP=noctis_pro.asgi:application

HOST=$HOST
PORT=$PORT
PYTHONPATH=$APP_DIR

CELERY_APP=noctis_pro
CELERY_LOGLEVEL=info

REDIS_URL=redis://127.0.0.1:6379/0

DICOM_PORT=11112
DICOM_AET=NOCTIS_SCP

PUBLIC_URL=$PUBLIC_URL
EOF

# Optionally configure DuckDNS for a constant name
if [ -n "$DUCKDNS_SUBDOMAIN" ] && [ -n "$DUCKDNS_TOKEN" ]; then
	cat > /etc/noctis/duckdns.env <<EOD
DUCKDNS_SUBDOMAIN=$DUCKDNS_SUBDOMAIN
DUCKDNS_TOKEN=$DUCKDNS_TOKEN
EOD
	install -m 0755 "$APP_DIR/ops/duckdns-update.sh" /usr/local/bin/duckdns-update.sh
	cp "$APP_DIR/ops/duckdns-update.service" /etc/systemd/system/duckdns-update.service
	cp "$APP_DIR/ops/duckdns-update.timer" /etc/systemd/system/duckdns-update.timer
	
	systemctl daemon-reload
	systemctl enable --now duckdns-update.timer || true
fi

# Install systemd services for the app
cp "$APP_DIR/ops/noctis-web.service" /etc/systemd/system/noctis-web.service
cp "$APP_DIR/ops/noctis-celery.service" /etc/systemd/system/noctis-celery.service
cp "$APP_DIR/ops/noctis-dicom.service" /etc/systemd/system/noctis-dicom.service

systemctl daemon-reload
systemctl enable --now noctis-web.service noctis-celery.service noctis-dicom.service

# Render nginx site from template with the resolved domain(s) and paths
SERVER_NAMES="$AUTO_DOMAIN"
if [ -n "$FALLBACK_DOMAIN" ]; then
	SERVER_NAMES="$SERVER_NAMES $FALLBACK_DOMAIN"
fi
if [ -n "$DUCK_DOMAIN" ]; then
	SERVER_NAMES="$SERVER_NAMES $DUCK_DOMAIN"
fi
NGINX_SITE="/etc/nginx/sites-available/noctis"
sed -e "s|{{SERVER_NAME}}|$SERVER_NAMES|g" \
	-e "s|{{APP_DIR}}|$APP_DIR|g" \
	"$APP_DIR/ops/nginx-noctis.conf.template" > "$NGINX_SITE"
ln -sf "$NGINX_SITE" /etc/nginx/sites-enabled/noctis
rm -f /etc/nginx/sites-enabled/default

nginx -t
systemctl restart nginx

# Open firewall (ignore if ufw is not installed)
ufw allow "Nginx Full" || true
ufw allow 11112/tcp || true

# Try HTTPS for one or more names via nginx plugin
CERT_NAMES=("$AUTO_DOMAIN")
if [ -n "$FALLBACK_DOMAIN" ]; then CERT_NAMES+=("$FALLBACK_DOMAIN"); fi
if [ -n "$DUCK_DOMAIN" ]; then CERT_NAMES+=("$DUCK_DOMAIN"); fi

CERTBOT_ARGS=(--nginx --non-interactive --agree-tos --register-unsafely-without-email --redirect)
for d in "${CERT_NAMES[@]}"; do CERTBOT_ARGS+=( -d "$d" ); done
certbot "${CERTBOT_ARGS[@]}" || true

# Prefer https if a cert exists
FINAL_HOST="$PUBLIC_HOST"
if [ -d "/etc/letsencrypt/live/$PUBLIC_HOST" ]; then
	SCHEME="https"
else
	SCHEME="http"
fi

# Final message
echo
echo "Setup complete."
echo "Access URL: $SCHEME://$FINAL_HOST/"
echo "Admin: $SCHEME://$FINAL_HOST/admin-panel/"
echo "Worklist: $SCHEME://$FINAL_HOST/worklist/"
echo "Services: noctis-web, noctis-celery, noctis-dicom"