# Generated by Django 5.2.5 on 2025-08-18 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_viewer', '0001_initial'),
        ('worklist', '0003_alter_study_accession_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HounsfieldQAPhantom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('water_roi_coordinates', models.JSONField(help_text='ROI coordinates for water measurement')),
                ('air_roi_coordinates', models.JSONField(help_text='ROI coordinates for air measurement')),
                ('material_rois', models.JSONField(default=dict, help_text='Additional material ROI coordinates')),
                ('expected_water_hu', models.FloatField(default=0.0)),
                ('expected_air_hu', models.FloatField(default=-1000.0)),
                ('expected_materials', models.JSONField(default=dict, help_text='Expected HU values for materials')),
                ('water_tolerance', models.FloatField(default=5.0)),
                ('air_tolerance', models.FloatField(default=50.0)),
                ('material_tolerances', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HounsfieldCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('station_name', models.CharField(blank=True, max_length=100)),
                ('device_serial_number', models.CharField(blank=True, max_length=100)),
                ('rescale_slope', models.FloatField()),
                ('rescale_intercept', models.FloatField()),
                ('rescale_type', models.CharField(blank=True, max_length=20)),
                ('water_hu', models.FloatField(blank=True, null=True)),
                ('air_hu', models.FloatField(blank=True, null=True)),
                ('noise_level', models.FloatField(blank=True, null=True)),
                ('calibration_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('warning', 'Warning'), ('not_applicable', 'Not Applicable'), ('error', 'Error')], max_length=20)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_issues', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('water_deviation', models.FloatField(blank=True, null=True)),
                ('air_deviation', models.FloatField(blank=True, null=True)),
                ('linearity_check', models.FloatField(blank=True, null=True)),
                ('calibration_date', models.DateField(blank=True, null=True)),
                ('phantom_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worklist.series')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hu_calibrations', to='worklist.study')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
