# Generated by Django 5.2.5 on 2025-08-29 16:31

from django.db import migrations, models
import django.db.models.deletion


def populate_series_field(apps, schema_editor):
    """Populate the series field for existing annotations based on their image's series"""
    Annotation = apps.get_model('dicom_viewer', 'Annotation')
    
    # Update all existing annotations to have the series from their related image
    for annotation in Annotation.objects.all():
        if annotation.image and annotation.image.series:
            annotation.series = annotation.image.series
            annotation.save()


def reverse_populate_series_field(apps, schema_editor):
    """Reverse operation - nothing needed as we're just removing the field"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_viewer', '0002_hounsfieldqaphantom_hounsfieldcalibration'),
        ('worklist', '0003_alter_study_accession_number'),
    ]

    operations = [
        # Step 1: Add the series field as nullable
        migrations.AddField(
            model_name='annotation',
            name='series',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='worklist.series',
                db_index=True
            ),
        ),
        
        # Step 2: Populate the series field for existing records
        migrations.RunPython(
            populate_series_field,
            reverse_populate_series_field,
        ),
        
        # Step 3: Make the field non-nullable now that it's populated
        migrations.AlterField(
            model_name='annotation',
            name='series',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='worklist.series',
                db_index=True
            ),
        ),
        
        # Step 4: Add study field as nullable
        migrations.AddField(
            model_name='annotation',
            name='study',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='worklist.study',
                db_index=True
            ),
        ),
        
        # Step 5: Populate study field from series
        migrations.RunPython(
            lambda apps, schema_editor: [
                setattr(annotation, 'study', annotation.series.study) or annotation.save()
                for annotation in apps.get_model('dicom_viewer', 'Annotation').objects.all()
                if annotation.series
            ],
            lambda apps, schema_editor: None,
        ),
        
        # Step 6: Make study field non-nullable
        migrations.AlterField(
            model_name='annotation',
            name='study',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='worklist.study',
                db_index=True
            ),
        ),
    ]
