# Generated by Django 5.2.5 on 2025-08-30 07:44

from django.db import migrations, models
import django.db.models.deletion


def populate_reconstruction_job_study(apps, schema_editor):
    """Populate study field for existing ReconstructionJob records"""
    ReconstructionJob = apps.get_model('dicom_viewer', 'ReconstructionJob')
    
    # Update all existing reconstruction jobs to have study field from their series
    for job in ReconstructionJob.objects.all():
        if job.series and job.series.study:
            job.study = job.series.study
            job.save(update_fields=['study'])


def reverse_populate_reconstruction_job_study(apps, schema_editor):
    """Reverse operation - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_viewer', '0010_ensure_model_sync'),
        ('worklist', '0001_initial'),
    ]

    operations = [
        # First add the study field as nullable
        migrations.AddField(
            model_name='reconstructionjob',
            name='study',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='worklist.study', db_index=True),
        ),
        
        # Populate the study field for existing records
        migrations.RunPython(
            populate_reconstruction_job_study,
            reverse_populate_reconstruction_job_study,
        ),
        
        # Make the field non-nullable
        migrations.AlterField(
            model_name='reconstructionjob',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklist.study', db_index=True),
        ),
    ]
