# Generated by Django 5.2.5 on 2025-08-30 08:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_viewer', '0012_populate_measurement_relations'),
        ('worklist', '0003_alter_study_accession_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['layer', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reconstructionjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='annotation',
            new_name='dicom_viewe_user_id_943519_idx',
            old_name='dicom_viewer_annot_user_study_idx',
        ),
        migrations.RenameIndex(
            model_name='annotation',
            new_name='dicom_viewe_image_i_eb3c97_idx',
            old_name='dicom_viewer_annot_image_created_idx',
        ),
        migrations.RenameIndex(
            model_name='annotation',
            new_name='dicom_viewe_study_i_ef5762_idx',
            old_name='dicom_viewer_annot_study_type_idx',
        ),
        migrations.RenameIndex(
            model_name='annotation',
            new_name='dicom_viewe_created_2d6c06_idx',
            old_name='dicom_viewer_annot_created_idx',
        ),
        migrations.RenameIndex(
            model_name='dicomimagecache',
            new_name='dicom_viewe_image_i_320f41_idx',
            old_name='dicom_viewer_cache_img_win_idx',
        ),
        migrations.RenameIndex(
            model_name='dicomimagecache',
            new_name='dicom_viewe_last_ac_a5da5b_idx',
            old_name='dicom_viewer_cache_accessed_idx',
        ),
        migrations.RenameIndex(
            model_name='dicomimagecache',
            new_name='dicom_viewe_cache_k_d14222_idx',
            old_name='dicom_viewer_cache_key_idx',
        ),
        migrations.RenameIndex(
            model_name='measurement',
            new_name='dicom_viewe_user_id_ad78ba_idx',
            old_name='dicom_viewer_meas_user_study_idx',
        ),
        migrations.RenameIndex(
            model_name='measurement',
            new_name='dicom_viewe_study_i_855c8f_idx',
            old_name='dicom_viewer_meas_study_type_idx',
        ),
        migrations.RenameIndex(
            model_name='measurement',
            new_name='dicom_viewe_image_i_fa26cb_idx',
            old_name='dicom_viewer_meas_image_created_idx',
        ),
        migrations.RenameIndex(
            model_name='measurement',
            new_name='dicom_viewe_created_27bcd6_idx',
            old_name='dicom_viewer_meas_created_idx',
        ),
        migrations.RenameIndex(
            model_name='viewerperformancemetrics',
            new_name='dicom_viewe_user_id_236baf_idx',
            old_name='dicom_viewer_perf_user_op_time_idx',
        ),
        migrations.RenameIndex(
            model_name='viewerperformancemetrics',
            new_name='dicom_viewe_operati_db95ff_idx',
            old_name='dicom_viewer_perf_op_time_idx',
        ),
        migrations.RenameIndex(
            model_name='viewerperformancemetrics',
            new_name='dicom_viewe_timesta_ed4f9f_idx',
            old_name='dicom_viewer_perf_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='viewerperformancemetrics',
            new_name='dicom_viewe_success_e9c537_idx',
            old_name='dicom_viewer_perf_success_op_idx',
        ),
        migrations.RenameIndex(
            model_name='viewersession',
            new_name='dicom_viewe_user_id_0494b2_idx',
            old_name='dicom_viewer_user_study_idx',
        ),
        migrations.RenameIndex(
            model_name='viewersession',
            new_name='dicom_viewe_updated_8b3a43_idx',
            old_name='dicom_viewer_session_updated_idx',
        ),
        migrations.AddField(
            model_name='measurement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reconstructionjob',
            name='actual_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconstructionjob',
            name='cpu_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconstructionjob',
            name='error_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reconstructionjob',
            name='estimated_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconstructionjob',
            name='max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='reconstructionjob',
            name='memory_usage',
            field=models.BigIntegerField(blank=True, help_text='Peak memory usage in bytes', null=True),
        ),
        migrations.AddField(
            model_name='reconstructionjob',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='reconstructionjob',
            name='processing_node',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reconstructionjob',
            name='progress',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='reconstructionjob',
            name='result_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='reconstructionjob',
            name='result_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconstructionjob',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconstructionjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconstructionjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reconstructionjob',
            name='worker_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='viewersession',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dicomimagecache',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurement_type',
            field=models.CharField(choices=[('length', 'Length'), ('area', 'Area'), ('angle', 'Angle'), ('cobb_angle', 'Cobb Angle'), ('volume', 'Volume'), ('density', 'Density (HU)'), ('distance_3d', '3D Distance'), ('ellipse', 'Ellipse'), ('rectangle', 'Rectangle'), ('circle', 'Circle'), ('polyline', 'Polyline'), ('spline', 'Spline Curve')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='points',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='unit',
            field=models.CharField(choices=[('mm', 'Millimeters'), ('cm', 'Centimeters'), ('px', 'Pixels'), ('mm2', 'Square Millimeters'), ('cm2', 'Square Centimeters'), ('mm3', 'Cubic Millimeters'), ('cm3', 'Cubic Centimeters'), ('deg', 'Degrees'), ('rad', 'Radians'), ('hu', 'Hounsfield Units')], default='mm', max_length=16),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_measurements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reconstructionjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reconstructionjob',
            name='job_type',
            field=models.CharField(choices=[('mpr', 'Multiplanar Reconstruction'), ('mip', 'Maximum Intensity Projection'), ('minip', 'Minimum Intensity Projection'), ('bone_3d', 'Bone 3D Reconstruction'), ('mri_3d', 'MRI 3D Reconstruction'), ('vr', 'Volume Rendering'), ('curved_mpr', 'Curved MPR'), ('thick_slab', 'Thick Slab'), ('vessel_analysis', 'Vessel Analysis'), ('perfusion', 'Perfusion Analysis')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='reconstructionjob',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='reconstructionjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='viewerperformancemetrics',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='viewersession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='viewersession',
            name='session_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='viewersession',
            unique_together={('user', 'study')},
        ),
        migrations.AddIndex(
            model_name='reconstructionjob',
            index=models.Index(fields=['user', 'status'], name='dicom_viewe_user_id_ec842f_idx'),
        ),
        migrations.AddIndex(
            model_name='reconstructionjob',
            index=models.Index(fields=['series', 'job_type'], name='dicom_viewe_series__016746_idx'),
        ),
        migrations.AddIndex(
            model_name='reconstructionjob',
            index=models.Index(fields=['status', 'priority', '-created_at'], name='dicom_viewe_status_db564f_idx'),
        ),
        migrations.AddIndex(
            model_name='reconstructionjob',
            index=models.Index(fields=['-created_at'], name='dicom_viewe_created_c692c5_idx'),
        ),
        migrations.AddIndex(
            model_name='viewersession',
            index=models.Index(fields=['user', '-last_accessed'], name='dicom_viewe_user_id_87801b_idx'),
        ),
    ]
