name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 192.168.100.15
        username: noctis
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/noctis_pro
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate --settings=noctis_pro.settings_production
          python manage.py collectstatic --noinput --settings=noctis_pro.settings_production
          sudo systemctl restart noctis-django noctis-daphne noctis-celery
          echo "Deployment completed successfully"